//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public long appointment_id { get; set; }
        public Nullable<long> header_id { get; set; }
        public Nullable<long> personnel_id { get; set; }
        public Nullable<long> regionid { get; set; }
        public Nullable<long> districtid { get; set; }
        public string prevpositiontype { get; set; }
        public string previousposition { get; set; }
        public Nullable<double> previoussalary { get; set; }
        public Nullable<int> appointmenttype { get; set; }
        public string itemno { get; set; }
        public string page { get; set; }
        public string publication { get; set; }
        public Nullable<System.DateTime> datesigned { get; set; }
        public string datepublished { get; set; }
        public string prevemployee { get; set; }
        public Nullable<int> prevemployeestatus { get; set; }
        public Nullable<int> cssmcno { get; set; }
        public string funds { get; set; }
        public string name { get; set; }
        public Nullable<int> year { get; set; }
        public string designation { get; set; }
        public string personnelselection { get; set; }
        public string personnelselectiondesignation { get; set; }
        public string personnelofficer { get; set; }
        public string personnelofficerdesignation { get; set; }
        public Nullable<bool> issave { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<int> transtype { get; set; }
        public Nullable<int> nosatype { get; set; }
    }
}
