//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class child
    {
        public long child_id { get; set; }
        public Nullable<long> personnel_id { get; set; }
        public string childname { get; set; }
        public string childbirthdate { get; set; }
        public Nullable<int> childstatusid { get; set; }
        public Nullable<bool> isInactive { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<long> region_id { get; set; }
    }
}
