//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class civilservice
    {
        public long civilservice_id { get; set; }
        public Nullable<long> personnel_id { get; set; }
        public Nullable<long> region_id { get; set; }
        public string civilservicename { get; set; }
        public string rate { get; set; }
        public string examdate { get; set; }
        public string placeconducted { get; set; }
        public string civilservice_number { get; set; }
        public string releasedate { get; set; }
        public Nullable<bool> isInactive { get; set; }
        public Nullable<long> district_id { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
