//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEHRISEntities : DbContext
    {
        public DEHRISEntities()
            : base("name=DEHRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<civilservice> civilservices { get; set; }
        public virtual DbSet<educationalBackground> educationalBackgrounds { get; set; }
        public virtual DbSet<hris_applicants> hris_applicants { get; set; }
        public virtual DbSet<hris_personnel> hris_personnel { get; set; }
        public virtual DbSet<profilepicture> profilepictures { get; set; }
        public virtual DbSet<specialSkill> specialSkills { get; set; }
        public virtual DbSet<trainingAssignment> trainingAssignments { get; set; }
        public virtual DbSet<workExperience> workExperiences { get; set; }
        public virtual DbSet<training> trainings { get; set; }
        public virtual DbSet<type_ImportTemplateCategory> type_ImportTemplateCategory { get; set; }
        public virtual DbSet<applicant> applicants { get; set; }
        public virtual DbSet<templateImport> templateImports { get; set; }
        public virtual DbSet<templateImportDetail> templateImportDetails { get; set; }
        public virtual DbSet<transImport> transImports { get; set; }
        public virtual DbSet<transImportDetail> transImportDetails { get; set; }
    }
}
