//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class educationalbackground
    {
        public long educationalBackground_id { get; set; }
        public Nullable<long> personnel_id { get; set; }
        public string level { get; set; }
        public string school { get; set; }
        public string degreeEarned { get; set; }
        public string yearGraduated { get; set; }
        public string unitsCompleted { get; set; }
        public string dateFrom { get; set; }
        public string dateTo { get; set; }
        public string honorsReceived { get; set; }
        public Nullable<bool> isInActive { get; set; }
        public Nullable<System.DateTime> datetimestamp { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> section_id { get; set; }
    }
}
