//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class profilepicture
    {
        public long profilepicture_id { get; set; }
        public Nullable<long> personnel_id { get; set; }
        public Nullable<bool> isInActive { get; set; }
        public string filepath { get; set; }
        public string contentType { get; set; }
        public byte[] binaryImage { get; set; }
    }
}
