//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialSkill
    {
        public long specialSkill_id { get; set; }
        public long personnel_id { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> section_id { get; set; }
        public string specialSkillDescription { get; set; }
        public Nullable<bool> isInactive { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
