//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class templateImportDetail
    {
        public long templateImportDetailsID { get; set; }
        public Nullable<long> templateImportID { get; set; }
        public string columnname { get; set; }
        public bool isActive { get; set; }
        public int worksheetNo { get; set; }
        public string address { get; set; }
    }
}
