//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tools_ImportTemplateDetails
    {
        public long tools_ImportTemplateDetailsID { get; set; }
        public Nullable<long> tools_ImportTemplateID { get; set; }
        public string worksheetAddress { get; set; }
        public string CellAddress { get; set; }
        public string CellRange { get; set; }
    }
}
