//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class training
    {
        public long training_id { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> header_id { get; set; }
        public string title { get; set; }
        public string inclusiveDates { get; set; }
        public Nullable<int> noOfHours { get; set; }
        public string conductedBy { get; set; }
        public Nullable<bool> isInactive { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<bool> isScholarship { get; set; }
        public Nullable<long> division_id { get; set; }
        public Nullable<long> trainingModule_id { get; set; }
        public Nullable<long> category_id { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public Nullable<long> personnel_id { get; set; }
    }
}
