//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class training
    {
        public long trainingID { get; set; }
        public string title { get; set; }
        public Nullable<int> duration { get; set; }
        public string conductedBy { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public Nullable<long> personnelID { get; set; }
        public string remarks { get; set; }
        public string type { get; set; }
        public string method { get; set; }
        public Nullable<bool> isMandatory { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
