//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class transImportDetail
    {
        public long transImportDetailsID { get; set; }
        public Nullable<long> transImportID { get; set; }
        public Nullable<long> templateImportID { get; set; }
        public Nullable<long> templateImportDetailsID { get; set; }
        public string columnAddress { get; set; }
        public string value { get; set; }
    }
}
