//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class transImport
    {
        public long transImportID { get; set; }
        public Nullable<long> templateImportID { get; set; }
        public Nullable<System.DateTime> dateImported { get; set; }
        public Nullable<long> importBy { get; set; }
    }
}
