//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_ImportTemplateCategory
    {
        public long type_ImportTemplateCategoryID { get; set; }
        public Nullable<long> parentID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> dateLastUpdated { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
