//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ais_cdtransactiondetails
    {
        public long ais_cdtransactiondetails_id { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string payee { get; set; }
        public Nullable<long> hris_personnel_id { get; set; }
        public string control_no { get; set; }
        public Nullable<long> ais_expensetype_id { get; set; }
        public Nullable<long> ais_account_id { get; set; }
        public string objectcode { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string description { get; set; }
    }
}
