//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_importtemplatedetail
    {
        public long common_importtemplatedetail_id { get; set; }
        public Nullable<long> common_importtemplate_id { get; set; }
        public string title { get; set; }
        public string celladdress { get; set; }
        public string value1 { get; set; }
        public string value2 { get; set; }
        public Nullable<bool> iscellrange { get; set; }
        public Nullable<bool> isvoid { get; set; }
        public Nullable<bool> isvertical { get; set; }
        public Nullable<int> maxstep { get; set; }
        public Nullable<int> worksheetno { get; set; }
        public Nullable<bool> isusedefaultvalue { get; set; }
        public string defaultvalue { get; set; }
    }
}
