//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_importtransaction
    {
        public long common_importtransaction_id { get; set; }
        public string transactionname { get; set; }
        public Nullable<System.DateTime> transactiondate { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
