//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_importtempate
    {
        public long common_importtemplate_id { get; set; }
        public string title { get; set; }
        public Nullable<int> maxiteration { get; set; }
        public string value2 { get; set; }
    }
}
