//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_importtransactiondetail
    {
        public long common_importtransactiondetails_id { get; set; }
        public long common_importtransaction_id { get; set; }
        public string title { get; set; }
        public string directory { get; set; }
        public string filename { get; set; }
        public string tablename { get; set; }
        public Nullable<long> tableid { get; set; }
        public string description { get; set; }
    }
}
