//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hris_address
    {
        public long hris_address_id { get; set; }
        public string fulladdress { get; set; }
        public string addresstype { get; set; }
        public Nullable<long> hris_personnel_id { get; set; }
    }
}
