//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hris_birform2305
    {
        public string EXMPN_CERT_SEQ_NUM { get; set; }
        public string EMP_VER { get; set; }
        public string EMP_FORM_VER { get; set; }
        public string FTYPE_CODE { get; set; }
        public string DLN { get; set; }
        public string EFFECTIVE_DATE { get; set; }
        public string FILING_REASON { get; set; }
        public string FILING_DATE { get; set; }
        public string TIN { get; set; }
        public string BRANCH_CODE { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string TYPE_FILER { get; set; }
        public string SIGNATURE_YN { get; set; }
        public string ATTACHMENT_YN { get; set; }
        public string CIVIL_STATUS { get; set; }
        public string claims_yn { get; set; }
        public string AF { get; set; }
        public string PROCESS_YN { get; set; }
        public string CREATED_BY { get; set; }
        public string DATE_CREATED { get; set; }
        public string RDO_CODE { get; set; }
        public string ADD_NUM_BLDG { get; set; }
        public string ADD_STREET { get; set; }
        public string ADD_BRGY { get; set; }
        public string ADD_MUN_TOWN_CITY { get; set; }
        public string ADD_PROV { get; set; }
        public string ZIP_CODE { get; set; }
        public string P5TIN { get; set; }
        public string P5BCODE { get; set; }
        public string P5RDOCODE { get; set; }
        public string P5EMP_FNAME { get; set; }
        public string P5EMP_LNAME { get; set; }
        public string P5EMP_MNAME { get; set; }
        public string P5EMPLOYER_NAME { get; set; }
        public string P5ADD_num { get; set; }
        public string P5ADD_SUBD { get; set; }
        public string P5ADD_BRGY { get; set; }
        public string P5ADD_MUN { get; set; }
        public string P5ADD_PROV { get; set; }
        public string P5ADD_ZCODE { get; set; }
        public string WA_SIGNATURE_YN { get; set; }
        public string WA_CERT_DATE { get; set; }
        public string sps_empt_status { get; set; }
        public string SPOUSE_TIN { get; set; }
        public string SPOUSE_BCODE { get; set; }
        public string SPOUSE_LAST_NAME { get; set; }
        public string SPOUSE_FIRST_NAME { get; set; }
        public string SPOUSE_MIDDLE_NAME { get; set; }
        public string SPOUSE_EMPLOYER_TIN { get; set; }
        public string SPOUSE_EMPLOYER_BRANCH { get; set; }
        public string EMPLOYMENT_TYPE { get; set; }
        public string MAIN_EMPR_YN { get; set; }
        public string NUM_QUALIFIED_DEP { get; set; }
        public string FORM_STATUS { get; set; }
        public string Editor { get; set; }
        public string DATE_MODIFIED { get; set; }
        public string NUM_OF_DEPND_CALC { get; set; }
        public string UPDATE_REASON { get; set; }
        public string CIVIL_STATUS_CALC { get; set; }
        public string DEPD_CERT_SEQ_NUM { get; set; }
        public string DEP_VER { get; set; }
        public string DEPENDENT1_LAST_NAME { get; set; }
        public string DEPENDENT1_FIRST_NAME { get; set; }
        public string DEPENDENT1_MIDDLE_NAME { get; set; }
        public string DEP1BDate { get; set; }
        public string DEPENDENT1_RELATIONSHIP_CODE { get; set; }
        public string INCAPACITATED_FLAG1_YN { get; set; }
        public string active_flag1 { get; set; }
        public string dep1ModifiedBy { get; set; }
        public string Expr1071 { get; set; }
        public string dep1ErrorCode { get; set; }
        public string DEPENDENT2_LAST_NAME { get; set; }
        public string DEPENDENT2_FIRST_NAME { get; set; }
        public string DEPENDENT2_MIDDLE_NAME { get; set; }
        public string DEP2BDate { get; set; }
        public string DEPENDENT2_RELATIONSHIP_CODE { get; set; }
        public string INCAPACITATED_FLAG2_YN { get; set; }
        public string active_flag2 { get; set; }
        public string dep2ModifiedBy { get; set; }
        public string Expr1081 { get; set; }
        public string dep2ErrorCode { get; set; }
        public string DEPENDENT3_LAST_NAME { get; set; }
        public string DEPENDENT3_FIRST_NAME { get; set; }
        public string DEPENDENT3_MIDDLE_NAME { get; set; }
        public string DEP3BDate { get; set; }
        public string DEPENDENT3_RELATIONSHIP_CODE { get; set; }
        public string INCAPACITATED_FLAG3_YN { get; set; }
        public string active_flag3 { get; set; }
        public string dep3ModifiedBy { get; set; }
        public string Expr1091 { get; set; }
        public string dep3ErrorCode { get; set; }
        public string DEPENDENT4_LAST_NAME { get; set; }
        public string DEPENDENT4_FIRST_NAME { get; set; }
        public string DEPENDENT4_MIDDLE_NAME { get; set; }
        public string DEP4BDate { get; set; }
        public string DEPENDENT4_RELATIONSHIP_CODE { get; set; }
        public string INCAPACITATED_FLAG4_YN { get; set; }
        public string active_flag4 { get; set; }
        public string dep4ModifiedBy { get; set; }
        public string Expr1101 { get; set; }
        public string dep4ErrorCode { get; set; }
        public string SEX { get; set; }
        public string PLACE_OF_BIRTH { get; set; }
        public string MOTHER_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string CITIZENSHIP { get; set; }
        public string OTHER_CITIZENSHIP { get; set; }
        public string ID_TYPE { get; set; }
        public string ID_NUMBER { get; set; }
        public string ID_ISSUER { get; set; }
        public string ID_EFFECTIVE_DATE { get; set; }
        public string ID_EXPIRY_DATE { get; set; }
        public string ID_PLACE_ISSUE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string FOREIGN_ADDRESS { get; set; }
        public string WA_CONTACT_NUMBER { get; set; }
        public string RELATIONSHIP_START_DATE { get; set; }
        public string COUNTRY { get; set; }
        public string DATE_MODIFIED_REP { get; set; }
        public string DATE_MODIFIED_REPORT { get; set; }
        public long id { get; set; }
        public string BIRTH_DATE { get; set; }
    }
}
