//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hris_personnel
    {
        public long hris_personnel_id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string nameextension { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string placeofbirth { get; set; }
        public string sex { get; set; }
        public string civilstatus { get; set; }
        public string citizenship { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string bloodtype { get; set; }
        public string residentialaddress { get; set; }
        public string residentialzipcode { get; set; }
        public string residentialtelephoneno { get; set; }
        public string permanentaddress { get; set; }
        public string permanentzipcode { get; set; }
        public string permanenttelephoneno { get; set; }
        public string emailaddress { get; set; }
        public string cellphoneno { get; set; }
        public string agencyemployeeno { get; set; }
        public string tin_no { get; set; }
        public string gsis_no { get; set; }
        public string sss_no { get; set; }
        public string pagibig_no { get; set; }
    }
}
