//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_projectaccess
    {
        public long pm_projectaccess_id { get; set; }
        public Nullable<System.DateTime> accessdatetime { get; set; }
        public Nullable<int> accesstype { get; set; }
    }
}
