//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEHRISMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_school
    {
        public long sis_school_id { get; set; }
        public string sis_schoolname { get; set; }
        public Nullable<int> sis_schoolpopulation { get; set; }
        public string sis_school_type { get; set; }
        public string division_id { get; set; }
        public string district_id { get; set; }
        public string address { get; set; }
        public Nullable<long> sis_schooldistrict_id { get; set; }
        public Nullable<bool> ispriv { get; set; }
        public Nullable<long> sis_school_code { get; set; }
    }
}
